### ISSUE TITLE
Calling `nvim_buf_delete` for deleted preview buffers?

### ISSUE THREAD

**Issue by jaekyeom** [anuvyklack/fold-preview.nvim#1]
Hi,
I'm glad that this is now a separate plugin being more modular.

I'm seeing the following error sometimes:
```
Error executing vim.schedule lua callback: ...hare/nvim/plugged/fold-preview.nvim/lua/fold-preview.lua:170: Invalid buffer id: 238
stack traceback:
        [C]: in function 'nvim_buf_delete'
        ...hare/nvim/plugged/fold-preview.nvim/lua/fold-preview.lua:170: in function ''
        vim/_editor.lua: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

I believe this is related to the cause of https://github.com/anuvyklack/pretty-fold.nvim/pull/24.
Currently, it seems that only the `nvim_win_close` call (not the `nvim_buf_delete` call) is safeguarded, now:
https://github.com/anuvyklack/fold-preview.nvim/blob/21aaf89c1828dc673b1cda6a2bdcd2901d6d9010/lua/fold-preview.lua#L166-L175

Could you consider preventing the `nvim_buf_delete` call from being executed multiple times as well, by including it in the if statement, if you don't see any issues with it?

Thanks!

**Comment by anuvyklack** [comment]
Done in 34ab83c6e1dd4f5394bb6914fadb7ec04d955805
