### ISSUE TITLE
Can't use `h` and `j` keys

### ISSUE THREAD

**Issue by lopi-py** [anuvyklack/fold-preview.nvim#2]
when I use `h` key I get this
![image](https://user-images.githubusercontent.com/70210066/195706168-676e6990-c01d-4c8c-8550-98b3b7c788d8.png)
and `j` key directly does nothing(not moving the cursor)

**Comment by anuvyklack** [comment]
Need more info. According to the error-stack the error is occurs in neo-tree.

**Comment by lopi-py** [comment]
Ah right, seems related to neo-tree. I'll look into it, I lazy load both plugins, seems like when I load neo-tree before than fold-preview the issue occurs. I suspect that when neo-tree is loaded, fold-preview is loaded too in the neo-tree buffer so it maps to neo-tree(I use `h` and `j` in neo-tree to expand/collapse) and when I want to use it in a buffer, its mapping is still pointing to neo-tree, what do you think @anuvyklack 

**Edit**: I'm pretty sure that its caused by the above stuff, looking at the stack, it begins on keymap-amend and ends on neo-tree related
