### ISSUE TITLE
Is it possible to show preview when cursor enters the folded line?

### ISSUE THREAD

**Issue by ryuheechul** [anuvyklack/fold-preview.nvim#3]
I know `h` will show preview but of when I'm on the folded line it's to see preview, so it would be more efficient if there is a way to show preview when cursor is on the line (and when hide when cursor leaves, which is already the case).

Since I couldn't find this way from the repo, leaving a question here.

**Comment by anuvyklack** [comment]
Very interesting idea!

**Comment by anuvyklack** [comment]
Done

**Comment by ryuheechul** [comment]
Thanks! it works like a charm!

Initially I had an issue because I said `auto = true` without reading the doc carefully 😅.
But after setting it to integer (I set it for 100), it works great!!

Also it's super handy to preview automatically just by moving to folded lines and it allows me to navigate code quickly while maintaining folds 👍🏼 👏🏼
