### ISSUE TITLE
Preview isn't shifting on indented folds

### ISSUE THREAD

**Issue by RaafatTurki** [anuvyklack/fold-preview.nvim#4]
I can't remember if this was always the case but I've recently noticed the preview window not sitting directly above indented folds.
[showcase](https://asciinema.org/a/U1QTO4GqbB3JkRTBYW1XkGr6y)

**Comment by anuvyklack** [comment]
I faced this issue too. It happens to me today, after I updated to Neovim 0.8.2

**Comment by RaafatTurki** [comment]
Yes that's the version I'm on.
