### ISSUE TITLE
Preview window is not closing

### ISSUE THREAD

**Issue by Tainted-Fool** [anuvyklack/fold-preview.nvim#7]
The preview window is not closing on cursor move, changing mode, or buffer leaving.

Pressing `zc` and `h`
![image](https://github.com/anuvyklack/fold-preview.nvim/assets/19850526/bd6b256f-152b-4dba-a7bf-2c0d64d2157c)
![image](https://github.com/anuvyklack/fold-preview.nvim/assets/19850526/44042550-a740-440f-961b-9284251cda2c)

if I press `k` to move up the preview window stays
![image](https://github.com/anuvyklack/fold-preview.nvim/assets/19850526/bcd151dc-3515-4df3-902c-f8372ea79a0e)

I also notice syntax highlighting disappears when i press `zc` and `h` again
![image](https://github.com/anuvyklack/fold-preview.nvim/assets/19850526/3e0f19f2-5d73-43fa-9b62-a286f5bfea57)

Short gif showing issue
![WindowsTerminal_dacWqppeRZ](https://github.com/anuvyklack/fold-preview.nvim/assets/19850526/55ecf7c2-3240-4c56-b029-fa18f75b3dff)

**Comment by MOB-34** [comment]
got the same issue
do u have any solution?

**Comment by Tainted-Fool** [comment]
> got the same issue do u have any solution?

Nope, ended up disabling the plugin. It's definitely a nice feature to have

**Comment by cosmicbuffalo** [comment]
hey not 100% sure if this will fix the issue you're seeing but I was having some similar problems with syntax highlighting breaking after using the fold preview too. took a look into the implementation and #8 seems to have fixed my issue, maybe y'all can give it a try too.

**Comment by Tainted-Fool** [comment]
@cosmicbuffalo This fixed my issue 😁

In case anyone is experiencing this problem, here's how to fix it. Nvim version BTW
![image](https://github.com/anuvyklack/fold-preview.nvim/assets/19850526/523b740f-eac3-4427-8c59-c735e5c9af89)

Open `~/.local/share/nvim/lazy/fold-preview.nvim/lua/fold-preview.lua` and comment out line `198` and `203`
Run nvim and voila 
![WindowsTerminal_XHWvWvIwWd](https://github.com/anuvyklack/fold-preview.nvim/assets/19850526/8fe83750-835d-44a8-95e9-51ad47954d20)
